### ISSUE TITLE
Resizing the album cover

### ISSUE THREAD

**Issue by Thorkul** [sergey-vlasov/nulloy#47]
When I click on the album cover, if cover is more larger than screen, cover is cropped instead of resized.

Example, with cover of 2400x2400px on 1366x768px screen.
![capture du 2014-09-06 12 14 37](https://cloud.githubusercontent.com/assets/1025754/4175374/7ecee88e-35cf-11e4-89a5-225b38ccf3cd.png)
The cover is cropped in right and bottom edge.

Origin cover
![vitalic-rave-age_portrait_w858](https://cloud.githubusercontent.com/assets/1025754/4175387/f02e4542-35cf-11e4-8b00-6b9c71cb3378.jpg)

If is possible, i suggest to appear album cover in the Nulloy window on transparent background :
![capture du 2014-09-06 12 13 49 copie](https://cloud.githubusercontent.com/assets/1025754/4175392/39f47958-35d0-11e4-8e33-459dc7cff3ab.png)

**Comment by sergey-vlasov** [comment]
Implemented in 2b0fd52
