### ISSUE TITLE
"Title format" window is bigger than screen

### ISSUE THREAD

**Issue by Thorkul** [sergey-vlasov/nulloy#54]
Hi,
In *Preferences > Track informations > help*
"Title format" window is bigger than screen in screen resolution 1366x768.
It's impossible to read the window bottom, and no scroll bar appear.

**Comment by sergey-vlasov** [comment]
Oh, I'll try to fix it. Thanks for reporting!

**Comment by sergey-vlasov** [comment]
Fixed in b7b82c0
