### ISSUE TITLE
Feature: Allow the window to be resized to full screen. 

### ISSUE THREAD

**Issue by RockBreaking** [sergey-vlasov/nulloy#56]
Allow the window to be resized to full screen.  This would allow better resolution of the waveform to make clicking on the waveform more precise.

**Comment by sergey-vlasov** [comment]
You can maximize the window by double clicking the title bar. Also you can make the window full screen with <kbd>F11</kbd> or context menu.

If you want to make just the the waveform bigger, you can drag the splitter:
![waveform-height](https://cloud.githubusercontent.com/assets/717109/6489483/76120522-c2a7-11e4-955e-12878bbb15f4.png)

**Comment by RockBreaking** [comment]
Thank you!

**Comment by sergey-vlasov** [comment]
And of course you can also resize the window using the size grip in the right bottom corner:
![sizegrip](https://cloud.githubusercontent.com/assets/717109/6489660/db9dacba-c2a8-11e4-97c7-6cb1d8f67ec4.png)
