### ISSUE TITLE
"ten seconds back" batton

### ISSUE THREAD

**Issue by vitaly-zdanevich** [sergey-vlasov/nulloy#6]
Thank you for only one (that I know) solution for Linux - player with waveform instead of seekbar. I use it for listening long audio lectures - maybe you think about the possibilities to add the 4 buttons (with hotkeys):

1) one minute back
2) ten seconds back
3) ten seconds forward
4) one minute forward

I think many of your users will like it.

Thank you.

**Comment by sergey-vlasov** [comment]
Implemented in b671073
